apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management-api
  template:
    metadata:
      labels:
        app: customer-management-api
    spec:
      containers:
      - name: customer-management-api
        image: registry-1.docker.io/omerav10/customer-management-api:v5
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-management-api
spec:
  selector:
    app: customer-management-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

